### ISSUE TITLE
sensor messages cannot be streamed

### ISSUE THREAD

**Issue by gborghesan** [orocos/rtt_ros2_common_interfaces#8]
Hello!
I could not stream in a topic the sensor messages; looking at the other packages, I saw that they have different cmake directives. To fix that, I made the changes in the patch following the example.

[0001-fix-to-sensor-message.patch.txt](https://github.com/orocos/rtt_ros2_common_interfaces/files/6556121/0001-fix-to-sensor-message.patch.txt)

**Comment by meyerj** [comment]
Likely fixed by https://github.com/orocos/rtt_ros2_common_interfaces/pull/9. Thanks for the patch!
